# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7f1abe3-ffc2-445d-aeb2-4475d3fa0935";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0664-AF62";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data" =
    {
      device = "/dev/disk/by-uuid/F49CD4A19CD45FA2";
      fsType = "ntfs-3g";
      options = [
        "uid=1000"
        "gid=100"
        "rw"
        "user"
        "nofail"
        "x-gvfs-show"
        "windows_names"
        "prealloc"
      ];
      noCheck = true;
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e39710d-c801-4b3f-85cc-92db37a10efb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
